project:
  type: website
  output-dir: docs
  render:
  - "*.qmd"
  - "!tmp/"
  - "!external_files/"
  - "!archived/"
  - "!testing.qmd"
  - "!mofa_test.qmd"
  
bibliography: ref.bib 

website:
  title: "PSLS @ 3rd CMI-PB Challenge"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - icon: github
        href: https://github.com/psl-schaefer/cmi_pb_third_challenge
      - icon: twitter
        href: https://x.com/psl_schaefer
      - icon: linkedin
        href: https://www.linkedin.com/in/philipp-sl-schaefer/

format:
  html:
    html-math-method: mathjax
    theme: darkly
    css: styles.css
    toc: true
    toc-float: yes
    toc-depth: 3
    toc-expand: 1
    toc-location: right
    number-sections: true
    df-print: paged
    code-tools: true
    code-fold: true
    code-overflow: scroll
