---
title: "Overview"
---

# Notes

- On the [Modeling Strategy](info/modeling_info.qmd)

- On the [3. CMI-PB Challenge](info/challenge_info.qmd)

# Exploratory Data Analysis

- [Raw Data Overview](eda/raw_data_overview.qmd)

- [Filtered Data Overview](eda/filtered_data_overview.qmd)

- [Batch Effects Raw Data](eda/batch_effects_raw_data.qmd)

- [Batch Effects After Normalization](eda/batch_effects_after_normalization.qmd)

- [Batch Effects After Batch Correction / Integration](eda/batch_effects_after_integration.qmd)

- [Prediction Targets](eda/targets.qmd)

# Models

- [Metadata Models](models/metadata_model.qmd)

- [Single Omic Models after Normalization](models/single_omic_after_normalization.qmd)

- [Single Omic Models after Integration](models/single_omic_after_integration.qmd)

- [Literature Models](models/literature_model.qmd)

- [Model Selection Default](models/model_selection_default.qmd)

- [Model Selection (Targets based on Normalized Data)](models/model_selection_normalized.qmd)

- [Model Selection (Targets based on Integrated Data)](models/model_selection_integrated.qmd)

- [Model Selection Comparison](models/comparison.qmd)

# Others

- [MOFA Test](eda/mofa_test.qmd)